# Generated by Django 4.1.3 on 2022-11-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='assunto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
